Repository rh-hideout/pokeemerald-expansion, pull requests merged in 2021-07, with the labels that each got.

#1556 Include expansion_branches.h in global.h
  include/global.h
Labels: branch: battle_engine, type: bug, type: feature

#1558 Include expansion_branches.h in global.h
  include/global.h
Labels: branch: item_expansion, type: bug, type: feature

#1559 Include expansion_branches.h in global.h
  include/global.h
Labels: branch: pokemon_expansion, type: bug, type: feature

#1563 AI_IsTerrainAffected checks
  include/battle_ai_util.h
  src/battle_ai_main.c
  src/battle_ai_util.c
Labels: ai, branch: battle_engine

#1572 Assigned dummy anims to the front sprite of each Pikachu and Pichu special form
  src/data/pokemon_graphics/front_pic_anims.h
Labels: branch: pokemon_expansion, category: pokemon, type: bug, type: data
