Repository rh-hideout/pokeemerald-expansion, pull requests merged in 2024-10, with the labels that each got.

#5449 Fixes recoil moves not triggering berries if possible
  include/constants/battle_script_commands.h
  src/battle_script_commands.c
  test/battle/hold_effect/restore_hp.c
Labels: category: items, bugfix

#5379 Switch AI refactor + considers free switches
  include/battle.h
  include/battle_ai_util.h
  src/battle_ai_main.c
  src/battle_ai_switch_items.c
  src/battle_ai_util.c
  src/battle_main.c
  src/battle_script_commands.c
  test/battle/ai/ai_switching.c
Labels: new-feature, category: battle-ai, type: refactor

#5455 Remove trailing whitespace pass 10-2-2024 (Master)
  src/battle_ai_main.c
  src/data/graphics/pokemon.h
  src/data/pokemon/species_info/gen_9_families.h
  test/battle/ai/ai_switching.c
  test/battle/gimmick/dynamax.c
  test/battle/move_effect/pledge.c
Labels: type: cleanup

#5456 Remove trailing whitespace pass 10-2-2024 (Upcoming)
  src/battle_ai_switch_items.c
  src/battle_anim_rock.c
  src/battle_script_commands.c
  src/berry.c
  src/bike.c
  src/data/graphics/pokemon.h
  src/data/heal_locations_pkm_center.h
  src/data/pokemon/species_info/gen_9_families.h
  src/event_object_movement.c
  src/field_control_avatar.c
  src/field_player_avatar.c
  src/heal_location.c
  src/metatile_behavior.c
  src/overworld.c
  src/pokemon_sprite_visualizer.c
  test/battle/ai/ai_switching.c
  test/battle/gimmick/dynamax.c
  test/battle/move_effect/pledge.c
Labels: type: cleanup

#5075 Updated species defines
  include/constants/cries.h
  include/constants/species.h
  src/battle_ai_util.c
  src/battle_controller_player.c
  src/battle_dynamax.c
  src/battle_main.c
  src/battle_script_commands.c
  src/battle_util.c
  src/battle_z_move.c
  src/berry.c
  src/data/pokemon/form_change_table_pointers.h
  src/data/pokemon/form_change_tables.h
  src/data/pokemon/form_species_tables.h
  src/data/pokemon/pokedex_orders.h
  src/data/pokemon/species_info/gen_1_families.h
  src/data/pokemon/species_info/gen_2_families.h
  src/data/pokemon/species_info/gen_3_families.h
  src/data/pokemon/species_info/gen_4_families.h
  src/data/pokemon/species_info/gen_5_families.h
  src/data/pokemon/species_info/gen_6_families.h
  src/data/pokemon/species_info/gen_7_families.h
  src/data/pokemon/species_info/gen_8_families.h
  src/data/pokemon/species_info/gen_9_families.h
  src/pokemon_jump.c
  test/battle/ability/cud_chew.c
  test/battle/ability/embody_aspect.c
  test/battle/ability/galvanize.c
  test/battle/ability/grim_neigh.c
  test/battle/ability/moxie.c
  test/battle/ability/mummy.c
  test/battle/ability/pastel_veil.c
  test/battle/ability/quick_draw.c
  test/battle/ability/storm_drain.c
  test/battle/ability/switch_in_abilities.c
  test/battle/ability/volt_absorb.c
  test/battle/ability/zen_mode.c
  test/battle/ai/ai_switching.c
  test/battle/crit_chance.c
  test/battle/form_change/begin_battle.c
  test/battle/gimmick/dynamax.c
  test/battle/gimmick/terastal.c
  test/battle/hold_effect/ogerpon_mask.c
  test/battle/hold_effect/protective_pads.c
  test/battle/hold_effect/restore_stats.c
  test/battle/move_effect/chilly_reception.c
  test/battle/move_effect/explosion.c
  test/battle/move_effect/gastro_acid.c
  test/battle/move_effect/ivy_cudgel.c
  test/battle/move_effect/raging_bull.c
  test/battle/move_effect/role_play.c
  test/battle/move_effect_secondary/freeze.c
  test/battle/terrain/electric.c
  test/battle/terrain/grassy.c
  test/battle/terrain/misty.c
  test/battle/terrain/psychic.c
Labels: category: battle-mechanic, category: pokemon, type: data, type: cleanup

#5405 Add functionality to Poké Flute and Town Map
  asm/macros/battle_script.inc
  data/battle_scripts_2.s
  include/constants/battle_string_ids.h
  include/constants/items.h
  include/item_use.h
  include/strings.h
  src/battle_ai_switch_items.c
  src/battle_message.c
  src/battle_script_commands.c
  src/data/items.h
  src/item_use.c
  src/strings.c
Labels: new-feature

#5436 Fix duplicating flute bug
  include/party_menu.h
  src/battle_controller_player.c
  src/party_menu.c
Labels: bugfix

#5468 Adds padding in AiLogicData
  include/battle.h
Labels: type: cleanup

#5447 Fixes to Protosynthesis, Quark Drive, Beast Boost, Orichalcum Pulse, Hadron Engine
  src/battle_main.c
  src/battle_script_commands.c
  src/battle_util.c
  test/battle/ability/protosynthesis.c
  test/battle/ability/quark_drive.c
Labels: category: ability, bugfix

#5453 updated Conversion 2 mechanics to 5+
  include/battle.h
  include/config/battle.h
  src/battle_main.c
  src/battle_script_commands.c
  src/data/moves_info.h
  test/battle/gimmick/terastal.c
  test/battle/move_effect/conversion_2.c
Labels: category: move effect

#5448 Add OW_UNION_DISABLE_CHECK and OW_FLAG_MOVE_UNION_ROOM_CHECK
  data/scripts/cable_club.inc
  data/scripts/pkmn_center_nurse.inc
  include/config/overworld.h
  include/link.h
  src/link.c
  src/union_room.c
Labels: new-feature, category: overworld

#5480 Permafix Rayquaza tail in cinematic
  graphics/rayquaza_scene/scene_3/rayquaza_tail.png
  graphics_file_rules.mk
  src/data/graphics/rayquaza_scene.h
Labels: type: cleanup

#5486 Fix AI tests using PASSES_RANDOMLY
  include/test/battle.h
  test/battle/ai/ai_switching.c
  test/test_runner_battle.c
Labels: bugfix, category: battle-tests

#5435 Simplify BS_FAINTED_MULTIPLE_1 double battle logic in openpartyscreen
  src/battle_controller_opponent.c
  src/battle_script_commands.c
Labels: type: cleanup

#5460 Heart Swap Move Animation
  data/battle_anim_scripts.s
  graphics/battle_anims/sprites/pinkvio_orb.png
  include/constants/battle_anim.h
  include/graphics.h
  src/battle_anim_effects_2.c
  src/battle_anim_psychic.c
  src/data/battle_anim.h
  src/graphics.c
Labels: category: move animation

#5457 Removes duplicate code in AI functions
  include/battle.h
  include/battle_util.h
  src/battle_ai_main.c
  src/battle_ai_util.c
  src/battle_main.c
  src/battle_util.c
Labels: category: battle-ai, type: cleanup

#5441 ShouldPivot type cleanup
  include/battle_ai_util.h
  src/battle_ai_main.c
  src/battle_ai_util.c
Labels: type: cleanup

#5497 Unify GetBattlerAbility/TerrainAffected to remove duplicate ai function
  include/battle_ai_util.h
  src/battle_ai_main.c
  src/battle_ai_util.c
  src/battle_main.c
  src/battle_util.c
Labels: category: battle-ai, type: cleanup

#5493 Updated ability popups for Skill Swap, Mummy/Lingering Aroma, Worry Seed, Simple Beam, fix Doodle/Role Play bugs
  data/battle_scripts_1.s
  src/battle_message.c
  src/battle_script_commands.c
  src/battle_util.c
  src/data/abilities.h
  test/battle/ability/mummy.c
  test/battle/move_effect/doodle.c
  test/battle/move_effect/role_play.c
  test/battle/move_effect/simple_beam.c
  test/battle/move_effect/skill_swap.c
  test/battle/move_effect/worry_seed.c
Labels: category: battle-mechanic, bugfix

#5467 Add Ion Deluge animation
  data/battle_anim_scripts.s
  src/battle_anim_electric.c
Labels: category: move animation

#5506 Cleanup extraneous function in battle_anim.h
  include/battle_anim.h
Labels: type: cleanup

#5501 Clean up Shedinja code
  src/evolution_scene.c
Labels: type: cleanup

#5462 ShouldSwitchIfGameStatePrompt Tests
  include/random.h
  src/battle_ai_switch_items.c
  test/battle/ai/ai_switching.c
Labels: category: battle-ai, category: battle-tests

#5438 Add various tests, add RNG_RANDOM_TARGET
  include/random.h
  src/battle_script_commands.c
  src/battle_util.c
  test/battle/ability/contrary.c
  test/battle/move_effect/belly_drum.c
  test/battle/move_effect/protect.c
  test/battle/move_effect/uproar.c
  test/battle/status1/burn.c
  test/battle/status1/frostbite.c
Labels: category: battle-tests

#5177 Adds new scripting macros to increase developer quality of life
  asm/macros/event.inc
  data/event_scripts.s
  include/constants/field_specials.h
  include/constants/pokedex.h
  include/event_object_movement.h
  include/field_specials.h
  include/pokedex.h
  src/event_object_movement.c
  src/field_specials.c
  src/scrcmd.c
Labels: new-feature, category: overworld

#5511 Clean up scrcmd PR
  include/field_specials.h
  src/field_specials.c
  src/scrcmd.c
Labels: type: cleanup

#5514 Merrp merge (12th of October)
  data/scripts/field_move_scripts.inc
  include/event_scripts.h
  src/braille_puzzles.c
  src/fldeff_dig.c
Labels: type: feature branch merge

#5446 Fixes Partner targeting and Acupressure/Ally Switch interaction
  src/battle_script_commands.c
  src/battle_util.c
  test/battle/move.c
  test/battle/move_effect/acupressure.c
Labels: category: battle-mechanic, bugfix

#5526 Add Costar Tests, Download Test for Doubles
  data/battle_scripts_1.s
  src/battle_util.c
  test/battle/ability/costar.c
  test/battle/ability/download.c
Labels: category: battle-tests

#5452 Refactor ShouldSwitchIfAllBadMoves
  include/battle.h
  include/battle_ai_main.h
  src/battle_ai_main.c
  src/battle_ai_switch_items.c
  src/battle_controller_opponent.c
  src/battle_controller_player_partner.c
  test/battle/ai/ai_switching.c
Labels: category: battle-ai, bugfix, type: refactor

#5520 Removes Crit Chance preproc
  src/battle_script_commands.c
  test/battle/crit_chance.c
Labels: category: battle-mechanic, type: cleanup

#5518 Add more later gen fishing mechanics
  include/config/item.h
  src/field_player_avatar.c
Labels: new-feature, category: overworld

#5538 Remove agbcc screenshots from gitignore
  .gitignore
Labels: type: cleanup, General

#5413 Added constant to expansion inclusive copyright magic number
  src/intro.c
Labels: type: cleanup

#5513 Move Relearner and Renaming From Summary Screen
  include/config/pokemon.h
  include/move_relearner.h
  include/pokemon_summary_screen.h
  include/strings.h
  src/move_relearner.c
  src/pokemon_storage_system.c
  src/pokemon_summary_screen.c
  src/strings.c
Labels: new-feature, General

#5490 Revival Blessing fixes + Using Lunar Blessing's animation
  data/battle_anim_scripts.s
  data/battle_scripts_1.s
  include/pokemon.h
  include/test/battle.h
  src/battle_script_commands.c
  src/pokemon.c
  test/battle/move_effect/revival_blessing.c
  test/test_runner_battle.c
Labels: category: battle-mechanic, bugfix

#5539 Add changelog header in PR template to aid automation
  .github/pull_request_template.md
Labels: type: documentation

#5532 Centralise AI Tests trainer name
  include/test/battle.h
  test/battle/ai/ai_flag_sequence_switching.c
  test/battle/ai/ai_switching.c
Labels: type: cleanup, category: battle-tests

#5546 Global is used instead of passed var
  src/battle_ai_util.c
Labels: category: battle-ai, bugfix

#5548 Remove now outdated information from readme
  README.md
Labels: type: cleanup

#5549 Updated Wring Out effects to match Eruption effects
  include/constants/battle_move_effects.h
  src/battle_ai_main.c
  src/battle_dynamax.c
  src/battle_util.c
  src/data/battle_move_effects.h
  src/data/moves_info.h
  test/battle/move.c
  test/battle/move_effect/power_based_on_target_hp.c
  test/battle/move_effect/power_based_on_user_hp.c
Labels: category: move effect, category: battle-tests, type: refactor

#5528 Tests: detect task leaks
  include/sound.h
  src/battle_main.c
  src/sound.c
  test/test_runner.c
  tools/mgba-rom-test-hydra/elf.h
  tools/mgba-rom-test-hydra/main.c
Labels: new-feature, category: battle-tests

#5552 Fix HGSS dex search printing wrong mon after selecting evos
  src/pokedex_plus_hgss.c
Labels: bugfix

#5475 Follower female fix
  include/event_object_movement.h
  include/global.fieldmap.h
  src/event_object_movement.c
  src/pokemon_sprite_visualizer.c
Labels: category: pokemon, bugfix, category: overworld

#5559 Healer ability tests
  include/random.h
  src/battle_util.c
  test/battle/ability/healer.c
Labels: category: battle-tests

#5556 Removed remaining line breaks from #3240 + Prefix wrap fix
  src/battle_message.c
Labels: type: cleanup

#5569 Add basic Steam Engine, Guard Dog Tests
  test/battle/ability/guard_dog.c
  test/battle/ability/steam_engine.c
Labels: category: battle-tests

#5572 Missing string_util.h include in mini_printf.c
  src/mini_printf.c
Labels: bugfix

#5558 Shed Skin chance fix
  src/battle_util.c
  test/battle/ability/shed_skin.c
Labels: type: cleanup

#5466 Should switch refactor to facilitate switch prediction
  include/battle.h
  include/battle_ai_main.h
  include/battle_ai_switch_items.h
  include/random.h
  src/battle_ai_main.c
  src/battle_ai_switch_items.c
  src/battle_ai_util.c
  src/battle_main.c
  src/battle_tv.c
  test/battle/ai/ai.c
  test/battle/ai/ai_flag_risky.c
  test/battle/ai/ai_switching.c
  test/test_runner_battle.c
Labels: category: battle-ai, bugfix, category: battle-tests, type: refactor

#5531 Mark all tests as used
  include/test/battle.h
  include/test/test.h
Labels: category: battle-tests

#5561 Fallback memmem implementation
  tools/mgba-rom-test-hydra/Makefile
  tools/mgba-rom-test-hydra/main.c
Labels: category: battle-tests

#5583 Fixes Magic Guard not preventing Salt Cure
  src/battle_util.c
  test/battle/move_effect/salt_cure.c
Labels: category: move effect, bugfix

#5582 Fixed broken Starting Terrain test
  test/battle/terrain/starting_terrain.c
Labels: bugfix, category: battle-tests

#5594 Fix unnecessary dependency scanning for test build and test rom names
  Makefile
Labels: type: sync, bugfix

#5601 Fixed 64px uncompressed followers
  src/data/object_events/object_event_pic_tables_followers.h
Labels: bugfix, category: sprite-issue

#5587 New AI flag for marking the two last Pokémon as Ace Pokémon.
  docs/tutorials/ai_flags.md
  include/constants/battle_ai.h
  src/battle_ai_switch_items.c
  src/battle_controller_opponent.c
  test/battle/ai/ai_double_ace.c
Labels: new-feature, category: battle-ai

#5599 Added compressed OW mon VRAM notice in config file
  include/config/overworld.h
Labels: type: documentation

#5609 Fixed a ball update oversight
  src/battle_main.c
Labels: type: cleanup

#5595 Added config to disable gender differences
  include/config/pokemon.h
  include/pokemon.h
  src/battle_anim_mons.c
  src/data/graphics/pokemon.h
  src/data/object_events/object_event_pic_tables_followers.h
  src/data/pokemon/species_info.h
  src/data/pokemon/species_info/gen_1_families.h
  src/data/pokemon/species_info/gen_2_families.h
  src/data/pokemon/species_info/gen_3_families.h
  src/data/pokemon/species_info/gen_4_families.h
  src/data/pokemon/species_info/gen_5_families.h
  src/data/pokemon/species_info/gen_6_families.h
  src/decompress.c
  src/event_object_movement.c
  src/pokemon.c
  src/pokemon_icon.c
  src/pokemon_storage_system.c
Labels: category: pokemon, new-feature

#5608 `AI_FLAG_ACE_POKEMON` takes into account separate trainers
  docs/tutorials/ai_flags.md
  include/pokemon.h
  src/battle_ai_switch_items.c
  src/battle_controller_opponent.c
  src/pokemon.c
Labels: category: battle-ai, type: cleanup

#5617 Restore test file dependencies so they're rebuilt properly
  Makefile
Labels: type: cleanup

#5570 Combines CalculateMoveDamage arguments into a struct
  include/battle_ai_util.h
  include/battle_util.h
  src/battle_ai_main.c
  src/battle_ai_switch_items.c
  src/battle_ai_util.c
  src/battle_script_commands.c
  src/battle_tv.c
  src/battle_util.c
  test/battle/ai/ai_switching.c
Labels: category: battle-ai, type: cleanup

#5625 Follow up for #5570
  include/battle_ai_util.h
  src/battle_ai_main.c
  src/battle_ai_switch_items.c
  src/battle_ai_util.c
Labels: type: cleanup
