Repository rh-hideout/pokeemerald-expansion, pull requests merged in 2024-07, with the labels that each got.

#5034 Added Ivy Cudgel Animation
  asm/macros/battle_anim_script.inc
  data/battle_anim_scripts.s
  graphics/battle_anims/sprites/cudgel.png
  graphics/pokemon/ogerpon/back.png
  graphics/pokemon/ogerpon/cornerstone/back.png
  graphics/pokemon/ogerpon/cornerstone/front.png
  graphics/pokemon/ogerpon/cornerstone/normal.pal
  graphics/pokemon/ogerpon/cornerstone/shiny.pal
  graphics/pokemon/ogerpon/front.png
  graphics/pokemon/ogerpon/hearthflame/back.png
  graphics/pokemon/ogerpon/hearthflame/front.png
  graphics/pokemon/ogerpon/hearthflame/normal.pal
  graphics/pokemon/ogerpon/hearthflame/shiny.pal
  graphics/pokemon/ogerpon/normal.pal
  graphics/pokemon/ogerpon/shiny.pal
  graphics/pokemon/ogerpon/wellspring/back.png
  graphics/pokemon/ogerpon/wellspring/front.png
  graphics/pokemon/ogerpon/wellspring/normal.pal
  graphics/pokemon/ogerpon/wellspring/shiny.pal
  include/constants/battle_anim.h
  include/graphics.h
  src/battle_anim.c
  src/battle_anim_effects_1.c
  src/data/battle_anim.h
  src/graphics.c
Labels: category: move animation

#5045 Pret Merge (27th of July)
  INSTALL.md
  include/constants/field_weather.h
  src/field_weather_effect.c
Labels: type: sync

#5039 Add Axe Kick animation
  data/battle_anim_scripts.s
  src/battle_anim_new.c
Labels: new-feature, category: move animation

#5061 Fixes Stalwart/Propeller Tail, Life Orb on confusion, Remove Status wrong battlescripts
  src/battle_script_commands.c
  src/battle_util.c
  test/battle/ability/stalwart.c
Labels: bugfix

#5057 Added AI Flags Documentation To Directory For New Documentation Site
  docs/SUMMARY.md
  docs/ai_flags.md
Labels: type: documentation

#4876 Only call RNG once when generating IVs in some cases
  src/pokemon.c
Labels: type: cleanup, General
