Repository rh-hideout/pokeemerald-expansion, pull requests merged in 2025-01, with the labels that each got.

#5889 Speed up tests in headless mode
  include/battle_gfx_sfx_util.h
  include/config/battle.h
  src/battle_controllers.c
  src/battle_gfx_sfx_util.c
  src/battle_intro.c
  src/battle_main.c
  src/battle_script_commands.c
  src/pokemon.c
  src/pokemon_animation.c
  test/test_runner.c
Labels: category: battle-tests

#5923 Added final Sparkling Aria+Shield Dust interaction test
  test/battle/ability/shield_dust.c
Labels: category: battle-tests

#5922 Fixed ace switching bugs
  src/battle_ai_switch_items.c
  test/battle/ai/ai_switching.c
Labels: category: battle-ai, bugfix

#5926 Fixes Trainer Slide messages causing corruption for recoil damage
  src/battle_script_commands.c
Labels: category: battle-mechanic, bugfix

#5925 Remove EWRAM gHpDealt (not needed anymore)
  include/battle.h
  src/battle_main.c
  src/battle_script_commands.c
Labels: type: cleanup

#5944 Fix DexNav static asserts
  src/dexnav.c
Labels: type: cleanup

#5833 Battle Weather Refactor
  data/battle_scripts_1.s
  include/battle_scripts.h
  include/battle_util.h
  include/constants/battle.h
  include/constants/battle_string_ids.h
  src/battle_dynamax.c
  src/battle_message.c
  src/battle_script_commands.c
  src/battle_util.c
Labels: category: battle-mechanic, type: refactor

#5337 Adds B_VAR_DIFFICULTY and related functions READ DESC
  asm/macros/event.inc
  data/event_scripts.s
  include/config/battle.h
  include/config/test.h
  include/constants/battle_partner.h
  include/constants/difficulty.h
  include/data.h
  include/difficulty.h
  src/battle_controller_player_partner.c
  src/battle_message.c
  src/battle_tower.c
  src/data.c
  src/data/battle_partners.h
  src/data/trainers.h
  src/difficulty.c
  src/new_game.c
  src/pokemon.c
  test/battle/trainer_control.c
  test/battle/trainer_control.h
  test/battle/trainer_control.party
  tools/trainerproc/main.c
Labels: category: battle-mechanic, new-feature, type: big feature

#5872 Easy customizable Hidden Move types
  include/data.h
  src/battle_main.c
  src/data/types_info.h
  test/battle/move_effect/hidden_power.c
Labels: category: battle-mechanic

#5679 Fly from Pokenav
  include/config/overworld.h
  include/overworld.h
  include/pokenav.h
  include/region_map.h
  src/field_effect.c
  src/field_region_map.c
  src/pokenav_main_menu.c
  src/pokenav_region_map.c
  src/region_map.c
Labels: new-feature

#5955 Removed references to HANDLE_EXPANDED_MOVE_NAME in docs
  docs/tutorials/how_to_new_move.md
Labels: type: documentation, type: cleanup

#5952 Field effect for cutting grass is missing setfieldeffectargument. Issue #5766
  data/scripts/field_move_scripts.inc
  include/event_scripts.h
  src/fldeff_cut.c
Labels: bugfix

#5950 Converted 2 various to callnative
  asm/macros/battle_script.inc
  include/constants/battle_script_commands.h
  src/battle_script_commands.c
  src/data/moves_info.h
  test/battle/move_effect/court_change.c
  test/battle/move_effect/speed_swap.c
Labels: type: data, type: cleanup, category: battle-tests

#5956 Last fix for Sparkling Aria / Covert Cloak / Shield Dust interaction
  include/battle_util.h
  src/battle_script_commands.c
  src/battle_util.c
  test/battle/ability/shield_dust.c
  test/battle/hold_effect/covert_cloak.c
Labels: category: move effect, bugfix

#5937 Added the Gen. 4+ berries to gBerryCrush_BerryData
  src/berry.c
Labels: category: items

#5960 Battle Weather Refactor oversight
  src/battle_util.c
Labels: category: battle-mechanic, bugfix

#5908 Add manual breaking back to "What will (mon) do?" message
  src/battle_controller_player.c
  src/battle_controller_safari.c
  src/battle_message.c
Labels: General

#5933 Fixes various Dynamax HP conversions/calculations
  include/battle.h
  include/battle_dynamax.h
  include/battle_util.h
  include/pokemon.h
  src/battle_controller_player.c
  src/battle_dynamax.c
  src/battle_script_commands.c
  src/battle_util.c
  src/pokemon.c
  test/battle/gimmick/dynamax.c
Labels: category: battle-mechanic, bugfix

#5971 Update scope.md (again)
  docs/scope.md
Labels: type: documentation

#5924 Shell Bell Clean up / Simplification and Tests
  include/battle.h
  src/battle_script_commands.c
  src/battle_util.c
  test/battle/hold_effect/life_orb.c
  test/battle/hold_effect/shell_bell.c
Labels: category: battle-mechanic, bugfix, type: cleanup

#5033 Arbitrary trainer scripts + on frame/trigger softlock prevention
  asm/macros/event.inc
  constants/gba_constants.inc
  data/maps/Route110/scripts.inc
  data/script_cmd_table.inc
  data/scripts/trainer_script.inc
  data/specials.inc
  include/event_scripts.h
  include/script.h
  include/test/overworld_script.h
  src/battle_ai_main.c
  src/battle_main.c
  src/difficulty.c
  src/event_object_movement.c
  src/fake_rtc.c
  src/field_control_avatar.c
  src/field_player_avatar.c
  src/main.c
  src/overworld.c
  src/scrcmd.c
  src/script.c
  src/script_pokemon_util.c
  src/trainer_see.c
  test/script.c
Labels: category: overworld

#5972 Rename AI_FLAG_PREFER_STRONGEST_MOVE
  docs/tutorials/ai_flags.md
  include/constants/battle_ai.h
  src/battle_ai_main.c
  src/battle_debug.c
Labels: type: cleanup

#5978 Removed OW_AUTO_SIGNPOST
  include/config/overworld.h
Labels: type: cleanup

#5984 Dynamic move type was ignored in doubles for spread moves
  src/battle_util.c
Labels: category: battle-mechanic, bugfix

#5967 Follo up for Innards Out / Future Sight interaction
  include/battle.h
  src/battle_script_commands.c
  src/battle_util.c
Labels: type: cleanup

#5964 Multiple removals of hardcoded move IDs
  include/battle_ai_util.h
  include/battle_util.h
  include/constants/battle.h
  src/battle_ai_main.c
  src/battle_ai_switch_items.c
  src/battle_ai_util.c
  src/battle_controller_player.c
  src/battle_script_commands.c
  src/battle_util.c
Labels: type: cleanup

#5996 Missed two uses of new hazard type enum
  src/battle_script_commands.c
Labels: type: cleanup

#5994 Debug menu and `createmon` additions/cleanup
  asm/macros/event.inc
  include/constants/weather.h
  src/debug.c
  src/script_pokemon_util.c
  test/pokemon.c
Labels: feature-request

#5954 Introduces Battler struct for the Battle Engine
  include/battle.h
  include/battle_util.h
  src/battle_ai_main.c
  src/battle_ai_switch_items.c
  src/battle_ai_util.c
  src/battle_arena.c
  src/battle_interface.c
  src/battle_main.c
  src/battle_script_commands.c
  src/battle_util.c
Labels: category: battle-mechanic, General

#6000 Free some IWRAM
  src/battle_anim_dragon.c
  src/digit_obj_util.c
  src/ereader_screen.c
  src/link.c
  src/pokedex_area_screen.c
Labels: type: cleanup

#6007 Ported Makefile fix from upcoming
  Makefile
Labels: bugfix

#5999 Use gCurrentMove instead of checking FF move
  src/battle_util.c
Labels: bugfix, type: cleanup

#5998 Future Sight Innards Out follow up for upcoming
  include/battle.h
  src/battle_script_commands.c
  src/battle_util.c
Labels: type: cleanup

#6008 Fixes Tera giving boost to dynamic bp moves
  src/battle_util.c
  test/battle/gimmick/terastal.c
Labels: category: battle-mechanic, bugfix

#6009 Fixes zmove trigger sprite on b button exit
  src/battle_controller_player.c
Labels: category: battle-mechanic, bugfix

#5936 Fixed a bunch of move anims
  data/battle_anim_scripts.s
  src/battle_anim_dark.c
  src/battle_anim_electric.c
  src/battle_anim_mon_movement.c
Labels: category: move animation, bugfix

#6012 Adds Liquid Ooze and Aromatic Mist test
  test/battle/ability/liquid_ooze.c
  test/battle/move_effect/aromatic_mist.c
Labels: category: battle-tests

#6014 Improved Hidden Power test
  test/battle/move_effect/hidden_power.c
Labels: category: battle-tests

#5916 Codify new expansion release schedule
  .github/pull_request_template.md
  docs/SUMMARY.md
  docs/team_procedures/schedule.md
  docs/team_procedures/scope.md
Labels: type: documentation

#6022 Workflow for Scope Discussion
  docs/team_procedures/scope.md
Labels: type: documentation

#6024 Wrong undefs
  src/battle_script_commands.c
Labels: type: cleanup

#6025 Add AI_FLAG_PREFER_HIGHEST_DAMAGE_MOVE
  docs/tutorials/ai_flags.md
  include/constants/battle_ai.h
  src/battle_ai_main.c
  test/battle/ai/ai_flag_risky.c
Labels: new-feature, category: battle-ai

#6020 Fixes self effect moves not procing for spread moves when battler 3 w…
  src/battle_script_commands.c
  test/battle/move_effects_combined/make_it_rain.c
Labels: category: battle-mechanic, bugfix

#6019 Ewram and unused function cleanup sweep
  include/battle_controllers.h
  include/contest.h
  include/field_weather.h
  include/global.fieldmap.h
  include/player_pc.h
  include/scanline_effect.h
  include/trainer_card.h
  src/battle_anim.c
  src/battle_controller_link_opponent.c
  src/battle_controller_link_partner.c
  src/battle_controller_opponent.c
  src/battle_controller_player.c
  src/battle_controller_player_partner.c
  src/battle_controller_recorded_opponent.c
  src/battle_controller_recorded_player.c
  src/battle_controller_safari.c
  src/battle_controller_wally.c
  src/battle_controllers.c
  src/bike.c
  src/credits.c
  src/decoration.c
  src/field_camera.c
  src/field_weather_effect.c
  src/fieldmap.c
  src/intro.c
  src/mystery_event_menu.c
  src/pokemon_storage_system.c
  src/scanline_effect.c
Labels: General

#5976 Restore lock/lockall/locktrainer/release/releaseall in triggers
  include/script.h
  src/scrcmd.c
Labels: bugfix, type: big feature

#6026 Fix Redirection Abilities Not Drawing in Ally Moves
  include/config/battle.h
  src/battle_util.c
  test/battle/ability/lightning_rod.c
  test/battle/move_effect/pledge.c
Labels: bug, category: battle-mechanic, bugfix

#6028 Add AI_FLAG_PREDICT_SWITCH
  include/battle.h
  include/battle_ai_util.h
  include/constants/battle_ai.h
  include/random.h
  src/battle_ai_main.c
  src/battle_ai_switch_items.c
  src/battle_ai_util.c
  src/battle_main.c
  test/battle/ai/ai_flag_predict_switch.c
Labels: new-feature, category: battle-ai

#6017 Config for move slot rearrangement in battle
  include/config/battle.h
  src/battle_controller_player.c
Labels: new-feature

#6039 Fix Symbiosis Needing battler Argument + Tests
  asm/macros/battle_script.inc
  data/battle_scripts_1.s
  src/battle_message.c
  src/battle_script_commands.c
  test/battle/ability/symbiosis.c
Labels: bug, category: battle-tests

#6044 Rename DexNav flags and vars
  include/config/dexnav.h
  src/dexnav.c
  src/field_control_avatar.c
  src/field_player_avatar.c
  src/start_menu.c
Labels: type: cleanup

#6045 Pret merge (17 of January)
  asm/macros/event.inc
  data/event_scripts.s
  data/script_cmd_table.inc
  data/scripts/mauville_man.inc
  graphics/cave_transition/enter.pal
  graphics/cave_transition/exit.pal
  include/bard_music.h
  include/constants/contest.h
  include/constants/global.h
  include/constants/songs.h
  include/constants/vars.h
  include/global.h
  include/rotating_gate.h
  include/sprite.h
  include/test/overworld_script.h
  src/bard_music.c
  src/battle_anim_fight.c
  src/contest.c
  src/data/bard_music/actions.h
  src/data/bard_music/adjectives.h
  src/data/bard_music/bard_sounds.h
  src/data/bard_music/battle.h
  src/data/bard_music/conditions.h
  src/data/bard_music/default_sound.h
  src/data/bard_music/endings.h
  src/data/bard_music/events.h
  src/data/bard_music/feelings.h
  src/data/bard_music/greetings.h
  src/data/bard_music/hobbies.h
  src/data/bard_music/length_table.h
  src/data/bard_music/lifestyle.h
  src/data/bard_music/misc.h
  src/data/bard_music/moves.h
  src/data/bard_music/people.h
  src/data/bard_music/pokemon.h
  src/data/bard_music/speech.h
  src/data/bard_music/status.h
  src/data/bard_music/time.h
  src/data/bard_music/trainer.h
  src/data/bard_music/trendysaying.h
  src/data/bard_music/voices.h
  src/data/bard_music/word_pitch.h
  src/easy_chat.c
  src/fldeff_flash.c
  src/intro.c
  src/list_menu.c
  src/mauville_old_man.c
  src/rotating_gate.c
  src/sprite.c
Labels: type: sync

#5048 Expanded Pokémon Follower transformation functionality
  include/config/overworld.h
  include/constants/form_change_types.h
  include/event_object_movement.h
  src/battle_util.c
  src/data/pokemon/form_change_tables.h
  src/daycare.c
  src/event_object_movement.c
  src/field_weather.c
  src/pokemon.c
  src/pokemon_storage_system.c
Labels: new-feature, category: overworld

#6051 Fixes HGSS dex not compiling currently
  src/pokedex_plus_hgss.c
Labels: bugfix

#6052 Fixes large battle messages being cut off instead of being prompted to advance
  src/battle_message.c
Labels: bugfix

#6053 Remove redundant line in Cmd_setcharge
  src/battle_script_commands.c
Labels: type: cleanup

#5605 Moved front animations frames to gSpeciesInfo
  src/data/pokemon/species_info.h
  src/data/pokemon/species_info/gen_1_families.h
  src/data/pokemon/species_info/gen_2_families.h
  src/data/pokemon/species_info/gen_3_families.h
  src/data/pokemon/species_info/gen_4_families.h
  src/data/pokemon/species_info/gen_5_families.h
  src/data/pokemon/species_info/gen_6_families.h
  src/data/pokemon/species_info/gen_7_families.h
  src/data/pokemon/species_info/gen_8_families.h
  src/data/pokemon/species_info/gen_9_families.h
  src/data/pokemon/species_info/shared_front_pic_anims.h
  src/data/pokemon_graphics/front_pic_anims.h
  src/pokemon.c
Labels: type: cleanup

#6027 IV/EV Info on Summary Screen
  graphics/summary_screen/iv_ev_tiles.png
  include/config/pokemon.h
  include/config/summary_screen.h
  include/constants/global.h
  include/pokemon_summary_screen.h
  src/graphics.c
  src/pokemon_summary_screen.c
Labels: new-feature

#6057 Clean up array access by using index instead of dereferencing the value
  src/battle_ai_main.c
  src/battle_ai_switch_items.c
  src/battle_controller_player.c
  src/battle_controller_player_partner.c
  src/battle_controller_recorded_opponent.c
  src/battle_controller_recorded_player.c
  src/battle_main.c
  src/battle_script_commands.c
  src/battle_util.c
  src/recorded_battle.c
Labels: type: cleanup

#6056 Fix Entrainment AI scoring bug
  src/battle_ai_main.c
  test/battle/move_effect/entrainment.c
Labels: category: battle-ai, bugfix

#5597 Moved mon pic tables to gSpeciesInfo + macro cleanup
  src/data/object_events/object_event_pic_tables_followers.h
  src/data/pokemon/species_info.h
  src/data/pokemon/species_info/gen_1_families.h
  src/data/pokemon/species_info/gen_2_families.h
  src/data/pokemon/species_info/gen_3_families.h
  src/data/pokemon/species_info/gen_4_families.h
  src/data/pokemon/species_info/gen_5_families.h
  src/data/pokemon/species_info/gen_6_families.h
  src/data/pokemon/species_info/gen_7_families.h
  src/data/pokemon/species_info/gen_8_families.h
  src/data/pokemon/species_info/gen_9_families.h
  src/pokemon.c
Labels: category: pokemon, type: cleanup

#6064 Add Steven Multi to debug menu
  data/scripts/debug.inc
  src/debug.c
Labels: General

#6066 Documentation for DisableStruct
  include/battle.h
Labels: type: documentation

#6068 Add a uniquely striking pair of brackets
  src/battle_ai_main.c
Labels: type: cleanup

#6069 Replace WEATHER_HAS_EFFECT with HasWeatherEffect
  include/battle.h
  include/battle_util.h
  src/battle_ai_main.c
  src/battle_ai_switch_items.c
  src/battle_controllers.c
  src/battle_main.c
  src/battle_script_commands.c
  src/battle_util.c
Labels: type: cleanup, type: refactor

#6063 Adds static assert for DamageCalculationData
  include/battle_util.h
Labels: category: battle-mechanic

#6071 Converts a bunch of defines to enums
  include/battle_setup.h
  include/battle_tower.h
  include/constants/battle.h
  include/constants/map_types.h
  include/constants/trade.h
  include/constants/trainers.h
  include/data.h
  include/frontier_util.h
  include/overworld.h
  include/pokemon.h
  include/pokemon_animation.h
  include/trainer_hill.h
  src/battle_bg.c
  src/battle_script_commands.c
  src/battle_setup.c
  src/battle_tower.c
  src/bike.c
  src/data/pokemon/trainer_class_lookups.h
  src/debug.c
  src/dexnav.c
  src/event_object_movement.c
  src/field_control_avatar.c
  src/field_effect.c
  src/field_screen_effect.c
  src/field_specials.c
  src/fldeff_flash.c
  src/fldeff_rocksmash.c
  src/frontier_util.c
  src/item_use.c
  src/overworld.c
  src/pokemon.c
  src/pokemon_animation.c
  src/pokemon_sprite_visualizer.c
  src/pokenav_match_call_list.c
  src/region_map.c
  src/scrcmd.c
  src/secret_base.c
  src/trainer_hill.c
Labels: type: cleanup

#6023 Fixes Rapid Spin / Toxic Debris interaction
  docs/tutorials/how_to_new_move.md
  include/constants/battle.h
  include/constants/battle_move_effects.h
  include/constants/battle_script_commands.h
  src/battle_ai_main.c
  src/battle_ai_switch_items.c
  src/battle_ai_util.c
  src/battle_script_commands.c
  src/battle_tv.c
  src/data/battle_move_effects.h
  src/data/moves_info.h
  test/battle/ability/shield_dust.c
  test/battle/ai/ai_powerful_status.c
  test/battle/hold_effect/covert_cloak.c
  test/battle/move_effect/rapid_spin.c
Labels: category: battle-mechanic, bugfix

#6072 Fixes Eject Pack triggering twice on Intimidate
  include/battle_util.h
  src/battle_script_commands.c
  src/battle_util.c
  test/battle/hold_effect/eject_pack.c
Labels: category: battle-mechanic, bugfix

#6059 Switch trapping AI will consider Trace
  include/battle_ai_util.h
  src/battle_ai_switch_items.c
  test/battle/ai/ai_switching.c
Labels: new-feature, category: battle-ai

#6074 Return the universe to a state of balanced quilibrium
  include/constants/battle_ai.h
Labels: type: cleanup

#6070 Cleaned up Debug Menu
  include/battle_message.h
  include/event_data.h
  src/battle_message.c
  src/battle_script_commands.c
  src/battle_setup.c
  src/debug.c
  src/event_data.c
  src/match_call.c
Labels: type: cleanup

#6078 Revert map related enum conversion
  include/constants/map_types.h
  include/overworld.h
  src/dexnav.c
  src/field_screen_effect.c
  src/fldeff_flash.c
  src/item_use.c
  src/overworld.c
Labels: bugfix

#6029 Remove gDecompressionBuffer
  asm/macros/event.inc
  include/bg.h
  include/config/overworld.h
  include/decompress.h
  include/hall_of_fame.h
  include/item_menu_icons.h
  include/mystery_gift_client.h
  include/sprite.h
  src/battle_anim.c
  src/battle_gfx_sfx_util.c
  src/battle_main.c
  src/battle_transition.c
  src/berry_blender.c
  src/berry_crush.c
  src/berry_tag_screen.c
  src/bg.c
  src/contest_link.c
  src/credits.c
  src/decompress.c
  src/ereader_screen.c
  src/event_object_movement.c
  src/field_effect.c
  src/fldeff_sweetscent.c
  src/hall_of_fame.c
  src/item_menu_icons.c
  src/link.c
  src/main_menu.c
  src/menu.c
  src/mystery_event_menu.c
  src/mystery_gift_client.c
  src/palette.c
  src/pokemon_sprite_visualizer.c
  src/pokenav_main_menu.c
  src/roulette.c
  src/save.c
  src/save_failed_screen.c
  src/scrcmd.c
  src/sprite.c
  src/trade.c
  src/union_room.c
Labels: type: big feature

#5731 Trainer Party Pools
  docs/tutorials/how_to_trainer_party_pool.md
  include/config/battle.h
  include/data.h
  include/trainer_pools.h
  src/battle_main.c
  src/data/battle_pool_rules.h
  src/trainer_pools.c
  test/battle/trainer_control.c
  test/battle/trainer_control.h
  test/battle/trainer_control.party
  tools/trainerproc/main.c
Labels: new-feature, type: big feature

#6105 Put Identifier and smol in gitignore
  .gitignore
Labels: type: cleanup

#6106 Fix Crash if something costs 0 in shop
  src/shop.c
Labels: bugfix

#6080 Introduces BattleTurnCounter to simplfy timer checks
  include/battle.h
  src/battle_ai_main.c
  src/battle_ai_switch_items.c
  src/battle_anim_effects_1.c
  src/battle_debug.c
  src/battle_dynamax.c
  src/battle_main.c
  src/battle_script_commands.c
  src/battle_util.c
Labels: category: battle-mechanic, type: refactor

#5982 Trainer Battle Parameter Consolidation
  asm/macros/battle_frontier/battle_dome.inc
  asm/macros/battle_frontier/battle_tower.inc
  asm/macros/battle_frontier/frontier_util.inc
  asm/macros/event.inc
  data/battle_scripts_1.s
  data/event_scripts.s
  data/maps/BattleFrontier_BattlePyramidFloor/scripts.inc
  data/maps/LavaridgeTown_Gym_1F/scripts.inc
  data/scripts/trainer_hill.inc
  include/battle_setup.h
  include/constants/battle.h
  include/constants/battle_setup.h
  include/constants/vars.h
  src/battle_ai_main.c
  src/battle_arena.c
  src/battle_bg.c
  src/battle_controller_link_opponent.c
  src/battle_controller_opponent.c
  src/battle_controller_recorded_opponent.c
  src/battle_dome.c
  src/battle_factory.c
  src/battle_gimmick.c
  src/battle_main.c
  src/battle_message.c
  src/battle_palace.c
  src/battle_pike.c
  src/battle_pyramid.c
  src/battle_script_commands.c
  src/battle_setup.c
  src/battle_tent.c
  src/battle_tower.c
  src/battle_transition.c
  src/battle_util.c
  src/cable_club.c
  src/frontier_util.c
  src/pokemon.c
  src/recorded_battle.c
  src/scrcmd.c
  src/secret_base.c
  src/trainer_hill.c
  src/trainer_see.c
  src/trainer_slide.c
  src/union_room_battle.c
  src/vs_seeker.c
  test/text.c
Labels: type: big feature

#5951 Add Code Entry functionality
  data/specials.inc
  docs/tutorials/how_to_code_entry.md
  include/constants/global.h
  include/naming_screen.h
  src/field_specials.c
  src/naming_screen.c
Labels: new-feature

#6098 Eject item ace flag switch AI fixes
  src/battle_ai_switch_items.c
  src/battle_util.c
  test/battle/ai/ai_switching.c
Labels: category: battle-ai, bugfix

#6097 Terrain function standarization
  src/battle_ai_util.c
  src/battle_main.c
  src/battle_util.c
Labels: type: cleanup

#6049 Updated trainer pic tutorial
  docs/tutorials/how_to_trainer_class.md
  docs/tutorials/how_to_trainer_pic.md
  include/data.h
  src/data.c
  src/pokemon.c
  src/trainer_pokemon_sprites.c
Labels: type: documentation, type: cleanup

#6073 Tera starstorm
  data/battle_anim_scripts.s
  graphics/battle_anims/sprites/starstorm_beam.png
  include/battle_anim.h
  include/constants/battle_anim.h
  include/graphics.h
  src/battle_anim_effects_1.c
  src/data/battle_anim.h
  src/graphics.c
Labels: category: move animation

#6114 Fix Double Iron Bash move animation crash on MyBoy/No$
  src/battle_anim_mons.c
Labels: bugfix

#6086 Duraludon battle animation
  graphics/pokemon/duraludon/anim_front.png
  graphics/pokemon/duraludon/front.png
  graphics/pokemon/duraludon/shiny.pal
  src/data/graphics/pokemon.h
  src/data/pokemon/species_info/gen_8_families.h
  src/data/pokemon_graphics/front_pic_anims.h
Labels: category: pokemon

#6116 Remove UnusedBattleInit from battle_bg.c
  src/battle_bg.c
Labels: type: cleanup

#6099 Match current gen behavior for battle environment after fishing
  include/config/item.h
  src/battle_setup.c
Labels: category: overworld

#6104 Fixed Hoenn dex off by 1 issues
  src/pokedex.c
Labels: bugfix

#6134 Removed stray semi-colon in AI code
  src/battle_ai_main.c
Labels: category: battle-ai, bugfix

#6127 Fixed AI not handling type effectiveness beyond x8
  include/battle.h
  include/battle_ai_util.h
  include/constants/battle_ai.h
  src/battle_ai_main.c
  src/battle_ai_switch_items.c
  src/battle_ai_util.c
Labels: category: battle-ai

#6137 Remove formToChangeInto (Unused)
  include/battle.h
Labels: type: cleanup

#5825 Implemented clear animation for also overworld pokemon
  src/scrcmd.c
Labels: bugfix, category: overworld

#6136 Replace BattleStruct members quickClawRandom/quickDrawRandom with locals
  include/battle.h
  src/battle_main.c
Labels: category: battle-mechanic, type: cleanup

#6088 Added Difficulty Fallback for Trainer Slides
  src/trainer_slide.c
Labels: type: cleanup

#6139 Clean up follow up for Simultaneous Reduction HP
  include/battle.h
  src/battle_script_commands.c
  src/battle_tv.c
  src/battle_util.c
Labels: type: cleanup

#6128 Remove global sBattler_AI
  include/battle_ai_main.h
  include/battle_ai_util.h
  src/battle_ai_main.c
  src/battle_ai_switch_items.c
  src/battle_ai_util.c
  src/battle_gfx_sfx_util.c
  src/battle_main.c
Labels: category: battle-ai, type: cleanup

#6140 Added some TO_DO tests
  test/battle/ability/aroma_veil.c
  test/battle/ability/chlorophyll.c
  test/battle/ability/electric_surge.c
  test/battle/ability/grassy_surge.c
  test/battle/ability/hydration.c
  test/battle/ability/misty_surge.c
  test/battle/ability/psychic_surge.c
  test/battle/ability/snow_cloak.c
  test/battle/ability/stance_change.c
  test/battle/gimmick/dynamax.c
Labels: category: battle-tests

#6151 Fixes battler mutation during the intim script
  data/battle_scripts_1.s
  test/battle/ability/intimidate.c
Labels: category: battle-mechanic, bugfix

#6145 Fixes Dynamic Moves types in SumScreen while in Battle
  src/battle_main.c
Labels: category: battle-mechanic, bugfix

#6154 Fixes Dragon Tail missing timing against Rocky Helmet / Iron Barbs
  asm/macros/battle_script.inc
  data/battle_scripts_1.s
  include/battle_scripts.h
  include/constants/battle_script_commands.h
  src/battle_script_commands.c
  src/data/battle_move_effects.h
  test/battle/move_effect/hit_switch_target.c
Labels: category: battle-mechanic, bugfix
